# Generated by Django 4.2.6 on 2024-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
