# Generated by Django 4.2.6 on 2024-04-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='totalPrice',
        ),
    ]
