# Generated by Django 4.2.6 on 2024-04-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_price_cart_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='totalPrice',
        ),
    ]
