# Generated by Django 4.2.6 on 2024-04-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_price_order_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totalPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='price',
        ),
    ]
